version: '3.7'

services:
  app:
    build:
      dockerfile: ./docker/Dockerfile
    volumes:
      - ./:/var/www/html:delegated
    networks:
      - app-tier

networks:
  app-tier:
    driver: bridge
